#!/usr/bin/env python3

import colors as c

print(c.red + '''
Enter your question below.
WELCOME TO EIGHTBALL!!!

Do you want to be a master programer?
'''+ c.reset)


answers = ['Yes.','No.','Maybe']
print(answers)

